HexToDecWithCustomException:HexToDecWithCustomException.o HexToDec.o
		g++ HexToDecWithCustomException.o HexToDec.o -o HexToDecWithCustomException
HexToDecWithCustomException.o: HexToDecWithCustomException.cpp
		g++ -c HexToDecWithCustomException.cpp
HexToDec.o: HexToDec.cpp
		g++ -c HexToDec.cpp
