HexToDecWithException:HexToDecWithException.o HexToDec.o
		g++ HexToDecWithException.o HexToDec.o -o HexToDecWithException
HexToDecWithException.o: HexToDecWithException.cpp
		g++ -c HexToDecWithException.cpp
HexToDec.o: HexToDec.cpp
		g++ -c HexToDec.cpp
