HexToDecWithCustomException:HexToDecWithCustomException.o HexFormatException.o
		g++ HexToDecWithCustomException.o HexFormatException.o -o HexToDecWithCustomException
HexToDecWithCustomException.o: HexToDecWithCustomException.cpp
		g++ -c HexToDecWithCustomException.cpp
HexFormatException.o: HexFormatException.cpp
		g++ -c HexFormatException.cpp
