TestBridgeHand: TestBridgeHand.o BridgeHand.o
		g++ TestBridgeHand.o  BridgeHand.o -o TestBridgeHand
TestBridgeHand.o: TestBridgeHand.cpp BridgeHand.h
		g++ -c TestBridgeHand.cpp
BridgeHand.o: BridgeHand.cpp BridgeHand.h
		g++ -c BridgeHand.cpp